FROM python:alpine
MAINTAINER Oleg Slavkin <oleg@slavkin.info>

ARG LINUXUSER=user

RUN pip3 install ipython
    
USER $LINUXUSER

# docker build -f Dockerfile.python --build-arg LINUXUSER=$(whoami) -t $(basename $(pwd) ) .
